server:
  port: 8080

spring:
  application:
    name: msa.user-service

  data:
    mongodb:
      uri: mongodb+srv://admin:admin@user-service-cluster.s9base9.mongodb.net/user_service?ssl=true&retryWrites=true&w=majority

  datasource:
    url: jdbc:postgresql://ep-orange-waterfall-a1ooripq-pooler.ap-southeast-1.aws.neon.tech/user_service?sslmode=require
    username: userdb_owner
    password: npg_qskwJ7fQ8YPM
    driver-class-name: org.postgresql.Driver

  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE