# .github/workflows/build.yml
name: Build & Deploy User Service

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
    
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t ghdrms1992/msa.user-service:latest .

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker push ghdrms1992/msa.user-service:latest

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/msa.user-service:latest
            docker stop user-service || true
            docker rm user-service || true
            docker run -d -p 8081:8080 --name user-service ${{ secrets.DOCKER_USER }}/msa.user-service:latest