# .github/workflows/deploy.yml
name: Deploy User Service

on:
  workflow_run:
    workflows: ["Build User Service"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/msa.user-service:latest
            docker stop user-service || true
            docker rm user-service || true
            docker run -d -p 8081:8080 --name user-service ${{ secrets.DOCKER_USER }}/msa.user-service:latest